<Project>
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company>OpenAEC Foundation</Company>
    <Copyright>Copyright (c) OpenAEC Foundation 2026</Copyright>
    <Version>0.2.1</Version>
    <Authors>3BM Bouwkunde</Authors>
  </PropertyGroup>
</Project>
